# Generated by Django 4.2.3 on 2023-07-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_wear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('S', 'S'), ('X', 'X'), ('XXL', 'XXL')], max_length=100)),
                ('how', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '4'), ('5', '5')], max_length=100)),
                ('map', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.wear')),
            ],
        ),
    ]
