# Generated by Django 4.2.3 on 2023-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_reklame'),
    ]

    operations = [
        migrations.AddField(
            model_name='wear',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
